### ISSUE TITLE
GDPR compliance?

### ISSUE THREAD

**Issue by AndersSweden** [denisonlinus/reading-ruler#1]
Can you please put in some text about how the extension (or/and you) does with my data? Google says that the app can read and change all the data at the websites I visit. A suggestion could be: "Nor the extension or I does anything at all with your data, it just provides you with a good service for when you read online."

**Comment by NoSubstitute** [comment]
Yes, please!
Since Chrome Extensions can be used by people all over the world, and new data privacy laws ([GDPR](https://gdpr-info.eu/)) in the European Union states that **anyone** offering services or products which EU citizens can use _have to_ abide by GDPR, this is something you must do. I also expect this is something that GitHub and Google, will soon require from all developers publishing content to their sites.

Basically, there needs only to be a simple text referencing what the extension/you can do and what it/you can't do. For example, any extension that is only local code, on the users computer, and doesn't connect back to the provider (you) would be perfectly safe to use.

But if it does allow the provider (you, or talks-back to a/your server in any way) access to user data, you would have to offer a Data Privacy Agreement with each and every organisation that uses the extension. A DPA that clearly, and in legalese, states what you will and will not do with the data, and if the data storage is outside the EU you would also have to abide by agreements like [EU-US Privacy Shield](https://www.privacyshield.gov), or something similar for where your data is stored.

**Comment by denisonlinus** [comment]
Hi, What do you thing about this faq?

Data Protection FAQ
===================

* Does the extension collect any user data?
** No, the Reading Ruler does not collect any kind of data.

* Does the extension track users?
** No, the Reading Ruler does not track users.

* Does the extension send data to any server?
** No, the Reading Ruler does not use any kind of server connection. All the processing is doing locally.

* Why does the extension need 'read and change websites' permission?
** Because the Reading Ruler needs the information of website elements to calculate and render the ruler.

**Comment by AndersSweden** [comment]
Fantastic!

Thanx.

/Anders Wockatz
Skalhamn, Sweden
WockatzIndeed <http://wockatzindeed.se>


*Apple Teacher*



Den tis 1 maj 2018 kl 16:38 skrev Denison Linus <notifications@github.com>:
